version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14  # Use the appropriate Node.js version for your Angular project
    commands:
      - npm install -g @angular/cli
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - ng build --prod
artifacts:
  files:
    - '**/*'
